#############################################################################
#
# Project Makefile
#
# (c) Tobias Bosch 2023
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := tests.cpp rgbc.cpp

# header files in this project
HEADERS := rgbc.hpp

# other places to look for files for this project
SEARCH  := 

# set RELATIVE to the next higher directory 
# and defer to the Makefile.* there
RELATIVE := ..

SERIAL_PORT ?= COM8

include $(RELATIVE)/Makefile.native